" Install pathogen to maintain git plugins
filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

filetype on
syntax on
set cindent
set nowrap
set tags=tags,/usr/src/linux-2.6/tags
"set tags=tags
"let Tlist_Show_One_File = 1
set background=dark
set laststatus=1
